In [ ]:
from halib import *
from src.config import Config

cfg = Config.from_custom_yaml_file("config/zruns/__base.yaml")
pprint(cfg)
pprint(cfg.cfg_name)
pprint(cfg.get_outdir())
cfg.save_to_outdir()

In [21]:
from halib import *

data = np.arange(48)
pprint(data)
H, W = 4, 12

block_h, block_w = 2, 4

rows, cols = H // block_h, W // block_w

pprint(f"{rows=}, {cols=}, {H=}, {W=}, {block_h=}, {block_w=}")

d1 = data.reshape(H, W)
pprint(d1)

d2 = data.reshape(rows, block_h, cols, block_w).swapaxes(1, 2)
pprint(d2)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
│      17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
│      34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])

'rows=2, cols=3, H=4, W=12, block_h=2, block_w=4'

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
│      [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
│      [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
│      [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]])

array([[[[ 0,  1,  2,  3],
│   │    [12, 13, 14, 15]],
│   │   
│   │   [[ 4,  5,  6,  7],
│   │    [16, 17, 18, 19]],
│   │   
│   │   [[ 8,  9, 10, 11],
│   │    [20, 21, 22, 23]]],
│      
│      
│      [[[24, 25, 26, 27],
│   │    [36, 37, 38, 39]],
│   │   
│   │   [[28, 29, 30, 31],
│   │    [40, 41, 42, 43]],
│   │   
│   │   [[32, 33, 34, 35],
│   │    [44, 45, 46, 47]]]])